# Generated by Django 5.0.1 on 2024-01-17 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productmodel_category'),
    ]

    operations = [
    ]
