# Generated by Django 5.0.1 on 2024-01-17 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20240117_1805'),
    ]

    operations = [
    ]
