# Generated by Django 5.0.1 on 2024-01-17 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20240117_1816'),
    ]

    operations = [
    ]
