# Generated by Django 5.0.1 on 2024-01-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20240117_1842'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
